
name: pybuild project

on: 
  push:
    branch:
      - main 

  workflow_dispatch:

jobs:
  pybuildjob1:
    runs-on: ubuntu-latest
    steps:
      - name: pybuildstep1
        uses: actions/checkout@v4
      - name: pybuildstep2
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: pybuildstep3
        run: pytest
        continue-on-error: true
      - name: checking error
        run: echo testing after error execution
      - name: install docker package
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: create docker image of the python
        run: |
          set -x
          docker version
          docker build -t vimpyimg .
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: vimalantonyraj@gmail.com
          password: Vimal@123
      - name: docker push
        run: |
          docker push vimpyimg
